### PR TITLE
now loads any selected tab on startup (i.e macro tab) from settings.json

### PR DESCRIPTION
**Pull request by qkdefus**
merged default tab changes to v4.408

### CODE REVIEW

**Comment by qkdefus** [comment]
its not adding `"DefaultTabOption":` "General",` to profile unless you click save button?

**Comment by Reetus** [comment]
Do we need to be able to select the default tab? would just remembering the last one they were on be better?

**Comment by qkdefus** [comment]
That would probably be better yes 😅

________________________________

**Comment by Reetus** [comment]
https://github.com/Reetus/ClassicAssist/pull/324

**Pull request closed without merging**
