### PR TITLE
Fixed issue #90 - will now properly select red / grey players added in Agent Friend List using Target Next Friend hotkey

### PR DESCRIPTION
**Pull request by qkdefus**

### CODE REVIEW

**Comment by qkdefus** [comment]
@Reetus im confused, how do I properly commit changes to master build ? lol

**Comment by Reetus** [comment]
you've made a complete mess of this...

Add a new PR with a single commit and a description of what it does, ie, 'Get Next Friend hotkey will allow all notorities'

One PR per feature, ie, don't add the extra priorities in the same PR (which im not sure I want)

**Comment by Timorio** [comment]
@qkdefus Thanks for the effort.  Did you get things straightened out?

**Comment by qkdefus** [comment]
@Reetus haha, yea i noticed.. No idea why vs kept adding all files to one PR. I tried several times to just commit single file 😅

**Comment by qkdefus** [comment]
@Timorio I think so, once i mange to make a proper PR 😀

**Pull request closed without merging**
